version: '3.7'

services:
  redis:
    image: letfn/redis
    ports:
      - 6369
    volumes:
      - ./etc/redis.conf:/etc/redis.conf
    labels:
      - "SERVICE_NAME=redis"

networks:
  default:
    external:
      name: kitt_default
