version: '3.7'

services:
  redis:
    image: letfn/redis
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 123:123/udp
    network_mode: host
    cap_add:
      - SYS_TIME
    volumes:
      - ./etc/redis.conf:/etc/redis.conf
